In [1]:
import numpy as np

file_path = 'DSB_data'

with open(file_path, 'rb') as f:
    raw_data = np.fromfile(f, dtype=np.float32)

complex_data = raw_data[::2] + 1j * raw_data[1::2]

X_real = complex_data.real
X_imag = complex_data.imag

DSB_data  = np.vstack([X_real, X_imag]).T  # Shape: (N, 2)
print(np.shape(DSB_data))


(528321, 2)


In [2]:
import numpy as np

file_path = 'USB_data'

with open(file_path, 'rb') as f:
    raw_data = np.fromfile(f, dtype=np.float32)

complex_data = raw_data[::2] + 1j * raw_data[1::2]

X_real = complex_data.real
X_imag = complex_data.imag

USB_data  = np.vstack([X_real, X_imag]).T  # Shape: (N, 2)
print(np.shape(USB_data))

(528320, 2)


In [3]:
row_to_remove = 528320
DSB_data = np.delete(DSB_data, row_to_remove, axis=0)
DSB_data = DSB_data.reshape(52832, 20)

In [4]:
USB_data = USB_data.reshape(52832, 20)

In [5]:
# 0 for DSB
# 1 for SSB - USB

In [6]:
target = np.zeros((DSB_data.shape[0], 1))  
DSB = np.hstack((DSB_data, target))
print( np.shape(DSB))

target = np.ones((USB_data.shape[0], 1))  
USB = np.hstack((USB_data, target))
print( np.shape(USB))


(52832, 21)
(52832, 21)


In [27]:
data = np.vstack((DSB, USB))
np.random.shuffle(data)

print("Combined dataset:" , np.shape(data)) 

X = data[:, :-1]  
y = data[:, -1]  

Combined dataset: (105664, 21)


In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
# 1. LOGISTIC REGRESSION

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 0.695074054795817

Confusion Matrix:
[[ 4178  6444]
 [    0 10511]]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.39      0.56     10622
         1.0       0.62      1.00      0.77     10511

    accuracy                           0.70     21133
   macro avg       0.81      0.70      0.66     21133
weighted avg       0.81      0.70      0.66     21133



In [29]:
# 2. SUPPORT VECTOR MACHINE

In [30]:
from sklearn.svm import SVC

model = SVC(kernel='rbf', random_state=42)  

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.999621445133204

Confusion Matrix:
[[10614     8]
 [    0 10511]]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10622
         1.0       1.00      1.00      1.00     10511

    accuracy                           1.00     21133
   macro avg       1.00      1.00      1.00     21133
weighted avg       1.00      1.00      1.00     21133



In [31]:
# 3. DECISION TREE CLASSIFIER

In [32]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 0.999810722566602

Confusion Matrix:
[[10621     1]
 [    3 10508]]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10622
         1.0       1.00      1.00      1.00     10511

    accuracy                           1.00     21133
   macro avg       1.00      1.00      1.00     21133
weighted avg       1.00      1.00      1.00     21133



In [33]:
# 4. RANDOM FOREST CLASSIFIER

In [34]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 1.0

Confusion Matrix:
[[10622     0]
 [    0 10511]]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10622
         1.0       1.00      1.00      1.00     10511

    accuracy                           1.00     21133
   macro avg       1.00      1.00      1.00     21133
weighted avg       1.00      1.00      1.00     21133



In [21]:
# 5. LIGHT GBM

In [22]:
from lightgbm import LGBMClassifier

model = LGBMClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("LightGBM Classification Report:")
print(classification_report(y_test, y_pred))


[LightGBM] [Info] Number of positive: 42321, number of negative: 42210
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004446 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 84531, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500657 -> initscore=0.002626
[LightGBM] [Info] Start training from score 0.002626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Accuracy: 1.0

Confusion Matrix:
[[10622     0]
 [    0 10511]]
LightGBM Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10622
         1.0       1.00      1.00      1.00     10511

    accuracy                           1.00     21133
   macro avg       1.00      1.00      1.00     21133
weighted avg       1.00      1.00      1.00     21133



In [23]:
# 6. K-Nearest Neighbors (KNN)

In [24]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("LightGBM Classification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 0.999905361283301

Confusion Matrix:
[[10620     2]
 [    0 10511]]
LightGBM Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10622
         1.0       1.00      1.00      1.00     10511

    accuracy                           1.00     21133
   macro avg       1.00      1.00      1.00     21133
weighted avg       1.00      1.00      1.00     21133



In [25]:
# 7. NAIVE BAYES 

In [26]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("LightGBM Classification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 1.0

Confusion Matrix:
[[10622     0]
 [    0 10511]]
LightGBM Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10622
         1.0       1.00      1.00      1.00     10511

    accuracy                           1.00     21133
   macro avg       1.00      1.00      1.00     21133
weighted avg       1.00      1.00      1.00     21133

